spring:
  profiles:
    active:
    - itest
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "db/changelog/changelog.xml"
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    root: info
